import { GoogleGenerativeAI } from "@google/generative-ai";
import { text } from "express"; 
import dotenv from "dotenv"

<<<<<<< HEAD
const genAI = new GoogleGenerativeAI("API_KEY_GOES_HERE");
=======
dotenv.config();

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
>>>>>>> 75d92436ac2b45dc66836dfd135e73096f93b305

async function genNewsLetter(reports) {


    const generationConfig = {
        temperature: 0,
        topP: 0.3,
        frequencyPenalty: 0.9,
        presencePenalty: 0.9,
    }


    const contextPromptStart = "You are a journalist hired to curate the top reports of the day. Note your job is to curate a newsletter and return a string in paragraph form. I am only giviing you a guide on how to think and make comparisons for your decisions. Your job entails the following: You would receive data in the form of an array of json objects. Each element of this array is an individual post. The format that the information is entered is { title: , description: , score : }. The title is the title of the post that a user has created on our website, the description is the description of events that occurred and the score is the result of the total number of likes minus the total number of dislikes on the post. Your job would be to go through each of these posts, and try to group similar events together. Similar events would be ones which have a lot of keywords that are similar with each other and the context of the events are similar as well. After grouping the similar events, I would like you to create a summarized article about individual events. If similar events are grouped together that means they must share something in common. For example: There is a house fire at bay, A lot of firefighters were at the scene of a fire near bay. These can be the same event so I want you to create an overarching title for these posts and write a summary about them. The way in which you know what to write about is from this idea of assigning weighting to different criterias. So the most liked post in a group of the ‘same’ event would be given higher priority, that is you make a statistical analysis and assume that the information in that post would be regarded as accurate due to a lot of people engaging/upvoting the post. The second way is by looking at other posts within that group of similar posts, your job is to analyze the posts and try to gather additional data that you can include in a summary that the first post might be lacking. Whether this may be from analyzing the second most upvoted comment or in the case of not a lot of upvotes you can analyze the posts and see what they have in common with each other to verify that the information is at least somewhat factual since a lot of people posted similar things.";
    const contextPromptStart2 = "After you have finished creating the summary and have the title of each of the events the next thing to do is the ordering in which the information appears in the newsletter. Your job is to have the most relevant, captivating reports occurring first to ensure that you can capture the readers attention. In order to do this you must devise an algorithm to determine the way in which reports would be ordered. You should think about overall upvotes tallied across all similar posts as one metric and you can also think about the frequency of a specific event being posted about as another metric. For example if event A has only 2 posts and the number of upvotes is 100 that is a lot, however, if we introduce event B which has 50 posts and the number of upvotes combined is 100, which event should be written first? You need to decide this. You can look at having a score = w1 * Total Engagement + w2 * Max Engagement Per Post + w3 * Post frequency where w1, w2, w3 are different weights assigned to each criterion. Once you have gotten the order, have the titles and the descriptive summaries of each unique event then you will formulate a newsletter where you have the title at the start and then the description."; 
    const returnFormat = "ONLY return the summarized string NOTHING else that is all just a string. The string should be formatted in the following way: Title of the event 1: Description of the event 1 Title of the event 2: Description of the event 2 Title of the event 3: Description of the event 3 ... Title of the event n: Description of the event n.";
    const training_data = "The following is a set of training data for you to recognize pattern with the inputted data and the preferred response : [ data : { title: 'Police gathering around Queens park', description: 'Anyone know whats happening??? I saw blood on the road and many police! Interested!!', score: 5 }, { title: 'Thief beside Kung fu tea', description: 'Please be mindful of you phone when passing through kung fu tea in dt trt, I just saw someones phone get stolen!', score: 10 }, { title: 'Someone getting shot near the park', description: 'I heard a huge gunshot sound when passing by the park today. Then I heard lots of police cars coming this way. Anyone know what happened?', score: 0 }, { title: 'New boba shop just opened near eaton', description: 'There was a huge line near eaton today. I heard it was because of the new boba store. Is it good?', score: 5 }, { title: 'Downtown getting unsafe', description: 'I saw someone reaching into a womans purse and took her phone. Gotta be careful!', score: 6 } , Output: Possible Criminal Activity Near Queens Park: Reports suggest a possible crime near Queens Park, with one witness reporting seeing blood on the road and a significant police presence.  Another report mentions hearing a gunshot near the park, followed by the arrival of numerous police cars.  While details remain unclear, the convergence of these reports warrants further investigation. Theft and Safety Concerns Downtown: Several incidents of theft have been reported in the downtown core. One post describes a phone theft near Kung Fu Tea, urging caution. Another describes a purse snatching, highlighting increasing safety concerns in the area.  These reports emphasize the need for increased vigilance and awareness of potential criminal activity downtown. New Boba Shop Opens Near Eaton Centre: A new boba shop near the Eaton Centre has attracted significant attention, with reports of long lines indicating considerable public interest. The shop's popularity suggests potential success and contributes to the vibrancy of the Eaton Centre area." + " " + 
                         "data : { title: 'Celebrity on Queen Street?', description: 'Sike!', score: 0 }, { title: 'Car accident on 401', description: 'There was a huge accident on 401 today. When I passed by, car parts were everywhere. Did anyone see?', score: 5 }, { title: 'Tragic incident', description: 'I heard on the news 12 people were injured on the highway….', score: 2 }, { title: 'NEW SHAKE SHAKE JUST OPENED', description: 'Tho, the line is crazyyyyy long!', score: 6 }, { title: 'Missing cat', description: 'My cat ran away from home at 8pm last night. She has orange fur and huge eyes. Please contact 437112345 if spotted.', score: 3 } , Output = Major Car Accident on Highway 401: There was a significant car accident on Highway 401 today, with one report describing car parts scattered across the roadway. Another source mentioned that 12 people were injured in the incident, though the specific details surrounding the crash remain unclear. Emergency responders were seen at the scene, and local news outlets have reported the tragic event. Authorities are likely continuing to investigate the cause of the crash. New Shake Shake Opens to Long Lines: In more local news, a new Shake Shake restaurant has just opened, quickly drawing attention with long lines of eager customers. Despite the wait, the buzz surrounding the new location is palpable, with many excited to try the latest addition to the local food scene. The popularity of the shop has added a lively energy to the area, although the crowds may be overwhelming for some. Missing Cat Reported: A local resident has reported their cat missing. The cat, described as having orange fur and large eyes, ran away from home last night around 8 PM. Anyone who may have spotted the cat is asked to contact the owner at 437-112-345. The community is urged to keep an eye out and help reunite the pet with its family." //+ " " + 
                         "data : { title: 'Police cars spotted at University of Toronto', description: 'Did anyone see the police cars outside of Myhal? I saw the police officers speaking to this student in cuffs', score: 4 }, { title: 'UofT unsafe!', description: 'Please be careful when walking down St George, a bunch of thieves dressed in all black just assaulted a random student on her way to class', score: 3 }, { title: 'Arrest at University of Toronto', description: 'A bunch of students were arrested for skipping their class', score: 0 }, { title: 'Bahen scaffolding safety issue', description: 'Be careful when passing by Bahen on the University of Toronto campus there is some debris that is falling when you walk under the construction site', score: 5 }, { title: 'Beware of wolves on the UofT Campus', description: 'University of Toronto is much better than University of Waterloo!!', score: 1 }, Output: Police Activity and Safety Concerns on UofT Campus: Reports of police presence and a student arrest near Myhal, coupled with accounts of an assault near St. George Street, raise safety concerns for students. Please remain vigilant and aware of your surroundings. Bahen Scaffolding Safety Issue: Exercise caution when walking near Bahen Centre on the University of Toronto campus due to falling debris from the construction scaffolding." + " " +
                         "data : { title: 'Bird flew into the window and broke it at Starbucks!', description: 'This morning while I was at the coffee shop a bird flew right into the window and broke it, it was traumatizing.', score: 4 }, { title: 'Someone was killed in Myhal!!', description: 'Omg, someone brought a gun to school and shot one of the professors, score: 0 }, Output: Bird Collision at Starbucks: A bird collided with a window at Starbucks, causing damage and a potentially traumatic experience for onlookers. Tragic Incident at Myhal: A fatal shooting incident occurred at Myhal, resulting in the death of a professor. The campus community is likely reeling from the tragic event, and authorities are likely investigating the situation further. "; + " " +
                         "data : { title: 'Bird flew into the window and broke it at Starbucks!', description: 'This morning while I was at the coffee shop a bird flew right into the window and broke it, it was traumatizing.', score: 6 }, { title: 'Someone was killed in Myhal!!', description: 'Omg, someone brought a gun to school and shot one of the professors, score: 2 }, Output: Bird Collision at Starbucks: A bird collided with a window at Starbucks, causing damage and a potentially traumatic experience for onlookers. Tragic Incident at Myhal: A fatal shooting incident occurred at Myhal, resulting in the death of a professor. The campus community is likely reeling from the tragic event, and authorities are likely investigating the situation further. "; + " " +
                         "data : { title: 'Bird flew into the window and broke it at Starbucks!', description: 'This morning while I was at the coffee shop a bird flew right into the window and broke it, it was traumatizing.', score: 3 }, { title: 'Someone was killed in Myhal!!', description: 'Omg, someone brought a gun to school amd shot one of the professors, score 2 }, Output: Tragic Incident at Myhal: A fatal shooting incident occurred at Myhal, resulting in the death of a professor. The campus community is likely reeling from the tragic event, and authorities are likely investigating the situation further. Bird Collision at Starbucks: A bird collided with a window at Starbucks, causing damage and a potentially traumatic experience for onlookers. "; + " " +
                         "data : { title: 'Fire alarm at Robarts Library', description: 'A fire alarm went off at Robarts Library earlier today. The building was evacuated, but no fire was found.', score: 3 }, { title: 'Bike theft near Convocation Hall', description: 'Someone stole my bike near Convocation Hall this afternoon. Please be cautious when parking your bikes!', score: 4 }, { title: 'Concert at Varsity Stadium', description: 'There's a live concert happening at Varsity Stadium tonight. Come join and enjoy the music!', score: 6 }, { title: 'Lost dog near Spadina', description: 'A small brown dog was spotted near Spadina Avenue. It looks lost, and the owner is nowhere to be found.', score: 2 }, { title: 'Road closure on College Street', description: 'College Street is temporarily closed for construction work. Avoid the area if possible.', score: 5 }, Output: Robarts Library Fire Alarm: A fire alarm was triggered at Robarts Library, leading to an evacuation.  No fire was ultimately discovered. Bike Theft Near Convocation Hall: A bicycle was reported stolen near Convocation Hall, prompting a warning to students and staff to be vigilant about bike security. Concert at Varsity Stadium: A live concert is taking place tonight at Varsity Stadium. Lost Dog Near Spadina Avenue: A small brown dog was seen near Spadina Avenue, appearing lost and without its owner. Road Closure on College Street: College Street is currently closed due to construction work, advising drivers to seek alternate routes. ";  //+ " " +
                         "data : { title: 'Gunshots near Union Station this morning', description: 'On my way to work, I heard loud gunshots near Union Station. People were panicking and running away. Anyone know what happened?', score: 7 }, { title: 'Police dealing with misfire at Union Station', description: 'Heard about some loud noises near Union Station today. Turns out it was a misfire inside the police headquarters. No danger to the public!', score: 10 }, { title: 'Traffic stopped at Dundas and Bay—what happened?', description: 'Saw traffic backed up and flashing lights near Dundas and Bay. Looked like a serious situation. Does anyone know more?', score: 5 }, { title: 'Car accident at Dundas and Bay sends driver to hospital', description: 'Passed by Dundas and Bay earlier and saw two cars that had collided. One driver was taken to the hospital. Hoping they’re okay.', score: 9 }, { title: 'Loud music and dancing at Nathan Phillips Square', description: 'Walked past Nathan Phillips Square and saw people dancing, waving flags, and playing loud music. Looked like a festival of some kind. Anyone know what it was?', score: 8 }, { title: 'Caribbean Festival brings energy to Nathan Phillips Square', description: 'Stopped by Nathan Phillips Square and found out it’s the annual Caribbean Festival! Great music, food stalls, and amazing performances celebrating Caribbean culture.', score: 11 }, { title: 'Brown dog wandering near Queen Street', description: 'Saw a lost-looking brown dog near Queen Street today. It didn’t have a collar. Hope it finds its owner soon!', score: 4 }, { title: 'Happy ending for lost dog on Queen Street', description: 'Spotted the brown dog near Queen Street earlier. Turns out someone reunited it with its owner thanks to a social media post!', score: 6 }, { title: 'Fire trucks on Spadina caused a scene', description: 'Saw several fire trucks rushing into a building on Spadina this morning. Didn’t see any smoke, but it looked urgent. Hope it wasn’t serious.', score: 7 }, { title: 'False alarm leads to fire trucks on Spadina', description: 'Turns out the fire trucks on Spadina this morning were responding to a false alarm in an office building. Thankfully, no fire or injuries.', score: 8 }, Output: Police Misfire Near Union Station: Loud noises heard near Union Station were determined to be a misfire within the police headquarters. No danger to the public was reported." + " " + 
                         "Car Accident and Hospitalization at Dundas and Bay: A car accident at the intersection of Dundas and Bay streets resulted in one driver being transported to the hospital. Reports indicate two vehicles collided. Caribbean Festival at Nathan Phillips Square: The annual Caribbean Festival took place at Nathan Phillips Square, featuring music, food stalls, and performances celebrating Caribbean culture. Numerous attendees enjoyed the vibrant atmosphere. False Alarm at Spadina Building: Fire trucks responded to a false alarm at an office building on Spadina. No fire or injuries were reported. Lost Dog Found on Queen Street: A brown dog, initially reported as wandering near Queen Street without a collar, was successfully reunited with its owner thanks to social media." + " " +
                         "data : { title: 'Loud explosion sound near Dundas and McCaul', description: 'On my way to class, I heard a loud explosion near Dundas and McCaul. People seemed startled but kept walking. Anyone know what happened?', score: 6 }, { title: 'Emergency vehicles near Dundas and McCaul', description: 'Saw fire trucks and ambulances rushing toward Dundas and McCaul this afternoon. The area was partially blocked off.', score: 7 }, { title: 'Strange light in the sky last night', description: 'Did anyone see the bright light in the sky around 9 PM? It looked like a shooting star but stayed visible longer than usual.', score: 5 }, { title: 'Meteor shower over Toronto?', description: 'I heard there was supposed to be a meteor shower last night. Could the bright light people saw be related?', score: 4 }, { title: 'Traffic jam on Spadina this morning', description: 'Traffic on Spadina was crawling today. Looked like something happened near College Street, but I couldn’t tell what.', score: 6 }, { title: 'Police near College and Spadina', description: 'There was a heavy police presence near College and Spadina this morning. Anyone know what’s going on?', score: 7 }, Output : Possible Incident Near Dundas and McCaul: Reports suggest a possible incident near Dundas and McCaul, with one witness reporting a loud explosion and another observing emergency vehicles rushing to the scene. The area was partially blocked off, suggesting a significant event. While details are still emerging, the convergence of these reports warrants further investigation. Morning Traffic Disruption on Spadina: A significant traffic jam was reported on Spadina this morning near College Street. A heavy police presence was also observed in the same area, suggesting a possible incident that caused the disruption. More information is needed to determine the exact cause of the traffic delay and police activity. Mysterious Light in Toronto Sky: Several reports describe a bright light in the sky last night, around 9 PM. While some speculate it may have been related to a meteor shower, further information is needed to confirm its nature. The unusual duration of the light has piqued public curiosity." + " " +
                         "data : { title: 'Super packed ttc', description: 'There is a ton of people at the subway station, It’s difficult to even go down the stairs to get on the train', score: 4 }, { title: 'Hello I am Bob!', description: 'Hi this is bob and this is newsworthy because my name is Bob newsworthy’, score: 1 }, { title: 'Everyone wearing shiny clothes’, description: 'Why is downtown filled with so many people wearing sparkly clothes?’, score: 3 }, { title: 'Nobel Prize winner Geoffrey Hinton spotted’, description: 'Spotted Geoffrey Hinton in a coffee shop in downtown toronto having coffee, could be a possible conference’, score: 4 }, { title: 'Taylor swift', description: 'Is taylor swift in toronto? I heard the news reporter say something along those lines and that could be why there are so many people in the subway!', score: 3 }, Output: Large Crowds in Downtown Toronto: Reports suggest unusually large crowds in downtown Toronto which can be linked to Taylor Swift’s arrival in the city. Another post observed many people wearing sparkly clothing which is in lieu of attire for a Taylor Swift concert. Nobel Prize Winner Spotted in Toronto:  Geoffrey Hinton, a Nobel Prize winner, was reportedly sighted in a downtown Toronto coffee shop. This sighting could indicate a conference or other event bringing notable figures to the city.]";

    const model = genAI.getGenerativeModel({ model: "gemini-1.5-flash" }, generationConfig);

    const prompt = contextPromptStart + "\n" + contextPromptStart2 + "\n" + training_data + "\n" + JSON.stringify(reports) + "\n" + returnFormat;

    const result = await model.generateContent(prompt);
    const response = result.response.text(); 

    console.log(response);
}

genNewsLetter()